# Reese Bottorff

## Assignment 8

### CS-150

In [1]:
import numpy as np
Array=np.array([[10,20],[30,40]])

In [2]:
Array_square=Array**2
print(Array_square)

[[ 100  400]
 [ 900 1600]]


In [4]:
Array_add=Array+100
print(Array_add)

[[110 120]
 [130 140]]


In [5]:
Array_multiply=Array*5
print(Array_multiply)

[[ 50 100]
 [150 200]]


In [7]:
Array_sqrt=np.sqrt(Array)
print(Array_sqrt)

[[3.16227766 4.47213595]
 [5.47722558 6.32455532]]


In [8]:
import numpy as np
ar1=np.arange(3,30,3).reshape(3,3)
print(ar1)

[[ 3  6  9]
 [12 15 18]
 [21 24 27]]


In [9]:
ar2=np.linspace(10,20,9).reshape(3,3)
print(ar2)

[[10.   11.25 12.5 ]
 [13.75 15.   16.25]
 [17.5  18.75 20.  ]]


In [10]:
mult=ar1*ar2
print(mult)

[[ 30.   67.5 112.5]
 [165.  225.  292.5]
 [367.5 450.  540. ]]


In [32]:
import numpy as np
X=np.load('process1.npy')
X

array([[52, 12, 81,  0, 58]], dtype=int32)

In [28]:
X1=np.load('process2.npy')
X1

array([[96,  4, 61, 16, 43]], dtype=int32)

In [29]:
X2=np.load('process3.npy')
X2

array([[38, 96, 45, 17, 58]], dtype=int32)

In [30]:
X3=np.load('process4.npy')
X3

array([[97, 21, 22, 25,  6]], dtype=int32)

In [31]:
X4=np.load('process5.npy')
X4

array([[77,  6, 19,  2, 74]], dtype=int32)

In [33]:
array1=np.vstack([X,X1,X2,X3,X4])

In [34]:
array1

array([[52, 12, 81,  0, 58],
       [96,  4, 61, 16, 43],
       [38, 96, 45, 17, 58],
       [97, 21, 22, 25,  6],
       [77,  6, 19,  2, 74]], dtype=int32)

In [35]:
np.mean(array1)

41.04